# 不要修改该文件，会自动生成，详见 http://gitlab.alibaba-inc.com/node/ci
before_script:
  - export PATH=$PWD/node_modules/.bin:$PATH
  - echo $PATH
  - time enclose install tnpm:tnpm
  - tnpm -v
test:
  image: reg.docker.alibaba-inc.com/dockerlab/node-ci:3.4.1
  script:
    - time tnpm i --no-cache --internal-oss-cache
    - node -e "console.log('%j, %j', process.versions, process.execPath)"
    - time tnpm run ci
  tags:
    - swarm
